[project]
name = "zincon"
version = "0.0.1"
description = "CLI for zinc skeletons"
requires-python = ">=3.8"
dependencies = [
    "click>=8.3",
]

[project.scripts]
zincon = "zincon:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"